name: Front end workflow

on:
    push:
        branches: [ master ]
        paths:
          - 'cv_IaC_v1/**'

env:
  AWS_REGION : ca-central-1

permissions:
    id-token: write   # This is required for requesting the JWT
    contents: read    # This is required for actions/checkout

jobs:
    FrontEndUpdate:
        runs-on: ubuntu-latest

        steps:
            - name: Git clone the repository
              uses: actions/checkout@v3
            
            - name: Install AWS CLI
              run: pip3 install awscli
            
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4.0.2
              with:
                  role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubAction-AssumeRoleWithAction 
                  role-session-name: GitHub_to_AWS_via_FederatedOIDC
                  aws-region: ${{ env.AWS_REGION }}
            
            - name: Upload files to S3
              run: aws s3 cp cv_IaC_v1 s3://thecodemango-cv/upload_test --recursive --exclude ".*" #TODO find a way to just upload changed file